site_name: Ballistix
site_description: The official documentation for the Ballistix project.

repo_name: maximilian-ba/ballistix
repo_url: https://github.com/maximilian-ba/ballistix

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["."]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - panzoom:
      always_show_hint: true
      include_selectors:
        - ".mermaid"

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    # Bright Mode
    - scheme: ballistix-light
      primary: custom
      accent: custom
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark Mode
    - scheme: ballistix-dark
      primary: custom
      accent: custom
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  language: en
  features:
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Architecture:
    - Context & Scope: architecture/03_context_and_scope.md
    - Design Decision: architecture/09-design-decisions.md
    - Decision Log (ADRs):
      - Overview: architecture/adr/index.md
      - 0001 - Core Abstraction: architecture/adr/0001-core-abstraction.md
      - 0002 - Time-Stepping Strategy: architecture/adr/0002-time-stepping-strategy.md
  - Project:
    - Contributing: project/contributing.md
    - License: project/license.md